/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct DocumentsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> DocumentsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> DocumentsApiClient<C> {
        DocumentsApiClient {
            configuration: configuration,
        }
    }
}

pub trait DocumentsApi {
    fn add_document(&self, environment_id: &str, collection_id: &str, version: String, file: ::models::File, metadata: &str) -> Box<Future<Item = ::models::DocumentAccepted, Error = Error<serde_json::Value>>>;
    fn delete_document(&self, environment_id: &str, collection_id: &str, document_id: &str, version: String) -> Box<Future<Item = ::models::DeleteDocumentResponse, Error = Error<serde_json::Value>>>;
    fn get_document_status(&self, environment_id: &str, collection_id: &str, document_id: &str, version: String) -> Box<Future<Item = ::models::DocumentStatus, Error = Error<serde_json::Value>>>;
    fn update_document(&self, environment_id: &str, collection_id: &str, document_id: &str, version: String, file: ::models::File, metadata: &str) -> Box<Future<Item = ::models::DocumentAccepted, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>DocumentsApi for DocumentsApiClient<C> {
    fn add_document(&self, environment_id: &str, collection_id: &str, version: String, file: ::models::File, metadata: &str) -> Box<Future<Item = ::models::DocumentAccepted, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/v1/environments/{environment_id}/collections/{collection_id}/documents".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_form_param("file".to_string(), unimplemented!())
            .with_form_param("metadata".to_string(), metadata.to_string())
            .execute(self.configuration.borrow())
    }

    fn delete_document(&self, environment_id: &str, collection_id: &str, document_id: &str, version: String) -> Box<Future<Item = ::models::DeleteDocumentResponse, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Delete, "/v1/environments/{environment_id}/collections/{collection_id}/documents/{document_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("document_id".to_string(), document_id.to_string())
            .execute(self.configuration.borrow())
    }

    fn get_document_status(&self, environment_id: &str, collection_id: &str, document_id: &str, version: String) -> Box<Future<Item = ::models::DocumentStatus, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/v1/environments/{environment_id}/collections/{collection_id}/documents/{document_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("document_id".to_string(), document_id.to_string())
            .execute(self.configuration.borrow())
    }

    fn update_document(&self, environment_id: &str, collection_id: &str, document_id: &str, version: String, file: ::models::File, metadata: &str) -> Box<Future<Item = ::models::DocumentAccepted, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/v1/environments/{environment_id}/collections/{collection_id}/documents/{document_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("document_id".to_string(), document_id.to_string())
            .with_form_param("file".to_string(), unimplemented!())
            .with_form_param("metadata".to_string(), metadata.to_string())
            .execute(self.configuration.borrow())
    }

}
