/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct TestYourConfigurationOnADocumentApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> TestYourConfigurationOnADocumentApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> TestYourConfigurationOnADocumentApiClient<C> {
        TestYourConfigurationOnADocumentApiClient {
            configuration: configuration,
        }
    }
}

pub trait TestYourConfigurationOnADocumentApi {
    fn test_configuration_in_environment(&self, environment_id: &str, version: String, step: &str, configuration_id: &str, configuration: &str, file: ::models::File, metadata: &str) -> Box<Future<Item = ::models::TestDocument, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>TestYourConfigurationOnADocumentApi for TestYourConfigurationOnADocumentApiClient<C> {
    fn test_configuration_in_environment(&self, environment_id: &str, version: String, step: &str, configuration_id: &str, configuration: &str, file: ::models::File, metadata: &str) -> Box<Future<Item = ::models::TestDocument, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/v1/environments/{environment_id}/preview".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("step".to_string(), step.to_string())
            .with_query_param("configuration_id".to_string(), configuration_id.to_string())
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_form_param("configuration".to_string(), configuration.to_string())
            .with_form_param("file".to_string(), unimplemented!())
            .with_form_param("metadata".to_string(), metadata.to_string())
            .execute(self.configuration.borrow())
    }

}
