/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct TrainingDataApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> TrainingDataApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> TrainingDataApiClient<C> {
        TrainingDataApiClient {
            configuration: configuration,
        }
    }
}

pub trait TrainingDataApi {
    fn add_training_data(&self, environment_id: &str, collection_id: &str, version: String, new_training_query: ::models::NewTrainingQuery) -> Box<Future<Item = ::models::TrainingQuery, Error = Error<serde_json::Value>>>;
    fn create_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String, training_example: ::models::TrainingExample) -> Box<Future<Item = ::models::TrainingExample, Error = Error<serde_json::Value>>>;
    fn delete_all_training_data(&self, environment_id: &str, collection_id: &str, version: String) -> Box<Future<Item = (), Error = Error<serde_json::Value>>>;
    fn delete_training_data(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String) -> Box<Future<Item = (), Error = Error<serde_json::Value>>>;
    fn delete_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, example_id: &str, version: String) -> Box<Future<Item = (), Error = Error<serde_json::Value>>>;
    fn get_training_data(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String) -> Box<Future<Item = ::models::TrainingQuery, Error = Error<serde_json::Value>>>;
    fn get_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, example_id: &str, version: String) -> Box<Future<Item = ::models::TrainingExample, Error = Error<serde_json::Value>>>;
    fn list_training_data(&self, environment_id: &str, collection_id: &str, version: String) -> Box<Future<Item = ::models::TrainingDataSet, Error = Error<serde_json::Value>>>;
    fn list_training_examples(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String) -> Box<Future<Item = ::models::TrainingExampleList, Error = Error<serde_json::Value>>>;
    fn update_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, example_id: &str, version: String, training_example_patch: ::models::TrainingExamplePatch) -> Box<Future<Item = ::models::TrainingExample, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>TrainingDataApi for TrainingDataApiClient<C> {
    fn add_training_data(&self, environment_id: &str, collection_id: &str, version: String, new_training_query: ::models::NewTrainingQuery) -> Box<Future<Item = ::models::TrainingQuery, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/v1/environments/{environment_id}/collections/{collection_id}/training_data".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_body_param(new_training_query)
            .execute(self.configuration.borrow())
    }

    fn create_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String, training_example: ::models::TrainingExample) -> Box<Future<Item = ::models::TrainingExample, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}/examples".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .with_body_param(training_example)
            .execute(self.configuration.borrow())
    }

    fn delete_all_training_data(&self, environment_id: &str, collection_id: &str, version: String) -> Box<Future<Item = (), Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Delete, "/v1/environments/{environment_id}/collections/{collection_id}/training_data".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .returns_nothing()
            .execute(self.configuration.borrow())
    }

    fn delete_training_data(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String) -> Box<Future<Item = (), Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Delete, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .returns_nothing()
            .execute(self.configuration.borrow())
    }

    fn delete_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, example_id: &str, version: String) -> Box<Future<Item = (), Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Delete, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}/examples/{example_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .with_path_param("example_id".to_string(), example_id.to_string())
            .returns_nothing()
            .execute(self.configuration.borrow())
    }

    fn get_training_data(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String) -> Box<Future<Item = ::models::TrainingQuery, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .execute(self.configuration.borrow())
    }

    fn get_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, example_id: &str, version: String) -> Box<Future<Item = ::models::TrainingExample, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}/examples/{example_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .with_path_param("example_id".to_string(), example_id.to_string())
            .execute(self.configuration.borrow())
    }

    fn list_training_data(&self, environment_id: &str, collection_id: &str, version: String) -> Box<Future<Item = ::models::TrainingDataSet, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/v1/environments/{environment_id}/collections/{collection_id}/training_data".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .execute(self.configuration.borrow())
    }

    fn list_training_examples(&self, environment_id: &str, collection_id: &str, query_id: &str, version: String) -> Box<Future<Item = ::models::TrainingExampleList, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}/examples".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .execute(self.configuration.borrow())
    }

    fn update_training_example(&self, environment_id: &str, collection_id: &str, query_id: &str, example_id: &str, version: String, training_example_patch: ::models::TrainingExamplePatch) -> Box<Future<Item = ::models::TrainingExample, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Put, "/v1/environments/{environment_id}/collections/{collection_id}/training_data/{query_id}/examples/{example_id}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Authorization".to_owned(),
            }))
            .with_auth(__internal_request::Auth::Basic)
            .with_query_param("version".to_string(), version.to_string())
            .with_path_param("environment_id".to_string(), environment_id.to_string())
            .with_path_param("collection_id".to_string(), collection_id.to_string())
            .with_path_param("query_id".to_string(), query_id.to_string())
            .with_path_param("example_id".to_string(), example_id.to_string())
            .with_body_param(training_example_patch)
            .execute(self.configuration.borrow())
    }

}
