/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeleteCollectionResponse {
  /// The unique identifier of the collection that is being deleted.
  #[serde(rename = "collection_id")]
  collection_id: String,
  /// The status of the collection. The status of a successful deletion operation is `deleted`.
  #[serde(rename = "status")]
  status: String
}

impl DeleteCollectionResponse {
  pub fn new(collection_id: String, status: String) -> DeleteCollectionResponse {
    DeleteCollectionResponse {
      collection_id: collection_id,
      status: status
    }
  }

  pub fn set_collection_id(&mut self, collection_id: String) {
    self.collection_id = collection_id;
  }

  pub fn with_collection_id(mut self, collection_id: String) -> DeleteCollectionResponse {
    self.collection_id = collection_id;
    self
  }

  pub fn collection_id(&self) -> &String {
    &self.collection_id
  }


  pub fn set_status(&mut self, status: String) {
    self.status = status;
  }

  pub fn with_status(mut self, status: String) -> DeleteCollectionResponse {
    self.status = status;
    self
  }

  pub fn status(&self) -> &String {
    &self.status
  }


}



