/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeleteEnvironmentResponse {
  /// The unique identifier for the environment.
  #[serde(rename = "environment_id")]
  environment_id: String,
  /// Status of the environment.
  #[serde(rename = "status")]
  status: String
}

impl DeleteEnvironmentResponse {
  pub fn new(environment_id: String, status: String) -> DeleteEnvironmentResponse {
    DeleteEnvironmentResponse {
      environment_id: environment_id,
      status: status
    }
  }

  pub fn set_environment_id(&mut self, environment_id: String) {
    self.environment_id = environment_id;
  }

  pub fn with_environment_id(mut self, environment_id: String) -> DeleteEnvironmentResponse {
    self.environment_id = environment_id;
    self
  }

  pub fn environment_id(&self) -> &String {
    &self.environment_id
  }


  pub fn set_status(&mut self, status: String) {
    self.status = status;
  }

  pub fn with_status(mut self, status: String) -> DeleteEnvironmentResponse {
    self.status = status;
    self
  }

  pub fn status(&self) -> &String {
    &self.status
  }


}



