/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ElementsEnrichmentOptions : An object representing the configuration options to use for the `elements` enrichment

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ElementsEnrichmentOptions {
  /// *For use with `elements` enrichments only.* The element extraction model to use. Models available are: `contract`.
  #[serde(rename = "model")]
  model: Option<String>
}

impl ElementsEnrichmentOptions {
  /// An object representing the configuration options to use for the `elements` enrichment
  pub fn new() -> ElementsEnrichmentOptions {
    ElementsEnrichmentOptions {
      model: None
    }
  }

  pub fn set_model(&mut self, model: String) {
    self.model = Some(model);
  }

  pub fn with_model(mut self, model: String) -> ElementsEnrichmentOptions {
    self.model = Some(model);
    self
  }

  pub fn model(&self) -> Option<&String> {
    self.model.as_ref()
  }

  pub fn reset_model(&mut self) {
    self.model = None;
  }

}



