/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GatewayList : Object containing gateways array.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GatewayList {
  /// Array of configured gateway connections.
  #[serde(rename = "gateways")]
  gateways: Option<Vec<::models::Gateway>>
}

impl GatewayList {
  /// Object containing gateways array.
  pub fn new() -> GatewayList {
    GatewayList {
      gateways: None
    }
  }

  pub fn set_gateways(&mut self, gateways: Vec<::models::Gateway>) {
    self.gateways = Some(gateways);
  }

  pub fn with_gateways(mut self, gateways: Vec<::models::Gateway>) -> GatewayList {
    self.gateways = Some(gateways);
    self
  }

  pub fn gateways(&self) -> Option<&Vec<::models::Gateway>> {
    self.gateways.as_ref()
  }

  pub fn reset_gateways(&mut self) {
    self.gateways = None;
  }

}



