/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ListEnvironmentsResponse {
  /// An array of [environments] that are available for the service instance.
  #[serde(rename = "environments")]
  environments: Option<Vec<::models::Environment>>
}

impl ListEnvironmentsResponse {
  pub fn new() -> ListEnvironmentsResponse {
    ListEnvironmentsResponse {
      environments: None
    }
  }

  pub fn set_environments(&mut self, environments: Vec<::models::Environment>) {
    self.environments = Some(environments);
  }

  pub fn with_environments(mut self, environments: Vec<::models::Environment>) -> ListEnvironmentsResponse {
    self.environments = Some(environments);
    self
  }

  pub fn environments(&self) -> Option<&Vec<::models::Environment>> {
    self.environments.as_ref()
  }

  pub fn reset_environments(&mut self) {
    self.environments = None;
  }

}



