/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NluEnrichmentCategories : An object that indicates the Categories enrichment will be applied to the specified field.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NluEnrichmentCategories {
}

impl NluEnrichmentCategories {
  /// An object that indicates the Categories enrichment will be applied to the specified field.
  pub fn new() -> NluEnrichmentCategories {
    NluEnrichmentCategories {
    }
  }

}



