/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NluEnrichmentConcepts : An object specifiying the concepts enrichment and related parameters.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NluEnrichmentConcepts {
  /// The maximum number of concepts enrichments to extact from each instance of the specified field.
  #[serde(rename = "limit")]
  limit: Option<i32>
}

impl NluEnrichmentConcepts {
  /// An object specifiying the concepts enrichment and related parameters.
  pub fn new() -> NluEnrichmentConcepts {
    NluEnrichmentConcepts {
      limit: None
    }
  }

  pub fn set_limit(&mut self, limit: i32) {
    self.limit = Some(limit);
  }

  pub fn with_limit(mut self, limit: i32) -> NluEnrichmentConcepts {
    self.limit = Some(limit);
    self
  }

  pub fn limit(&self) -> Option<&i32> {
    self.limit.as_ref()
  }

  pub fn reset_limit(&mut self) {
    self.limit = None;
  }

}



