/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct QueryRelationsArgument {
  #[serde(rename = "entities")]
  entities: Option<Vec<::models::QueryEntitiesEntity>>
}

impl QueryRelationsArgument {
  pub fn new() -> QueryRelationsArgument {
    QueryRelationsArgument {
      entities: None
    }
  }

  pub fn set_entities(&mut self, entities: Vec<::models::QueryEntitiesEntity>) {
    self.entities = Some(entities);
  }

  pub fn with_entities(mut self, entities: Vec<::models::QueryEntitiesEntity>) -> QueryRelationsArgument {
    self.entities = Some(entities);
    self
  }

  pub fn entities(&self) -> Option<&Vec<::models::QueryEntitiesEntity>> {
    self.entities.as_ref()
  }

  pub fn reset_entities(&mut self) {
    self.entities = None;
  }

}



