/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct QueryRelationsResponse {
  #[serde(rename = "relations")]
  relations: Option<Vec<::models::QueryRelationsRelationship>>
}

impl QueryRelationsResponse {
  pub fn new() -> QueryRelationsResponse {
    QueryRelationsResponse {
      relations: None
    }
  }

  pub fn set_relations(&mut self, relations: Vec<::models::QueryRelationsRelationship>) {
    self.relations = Some(relations);
  }

  pub fn with_relations(mut self, relations: Vec<::models::QueryRelationsRelationship>) -> QueryRelationsResponse {
    self.relations = Some(relations);
    self
  }

  pub fn relations(&self) -> Option<&Vec<::models::QueryRelationsRelationship>> {
    self.relations.as_ref()
  }

  pub fn reset_relations(&mut self) {
    self.relations = None;
  }

}



