/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SourceOptionsObject : Object that defines a Salesforce document object type crawl with this configuration.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SourceOptionsObject {
  /// The name of the Salesforce document object to crawl. For example, `case`.
  #[serde(rename = "name")]
  name: String,
  /// The maximum number of documents to crawl for this document object. By default, all documents in the document object are crawled.
  #[serde(rename = "limit")]
  limit: Option<i32>
}

impl SourceOptionsObject {
  /// Object that defines a Salesforce document object type crawl with this configuration.
  pub fn new(name: String) -> SourceOptionsObject {
    SourceOptionsObject {
      name: name,
      limit: None
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> SourceOptionsObject {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_limit(&mut self, limit: i32) {
    self.limit = Some(limit);
  }

  pub fn with_limit(mut self, limit: i32) -> SourceOptionsObject {
    self.limit = Some(limit);
    self
  }

  pub fn limit(&self) -> Option<&i32> {
    self.limit.as_ref()
  }

  pub fn reset_limit(&mut self) {
    self.limit = None;
  }

}



