/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Timeslice {
  /// The type of aggregation command used. For example: term, filter, max, min, etc.
  #[serde(rename = "type")]
  type_: Option<String>,
  #[serde(rename = "results")]
  results: Option<Vec<::models::AggregationResult>>,
  /// Number of matching results.
  #[serde(rename = "matching_results")]
  matching_results: Option<i32>,
  /// Aggregations returned by the Discovery service.
  #[serde(rename = "aggregations")]
  aggregations: Option<Vec<::models::QueryAggregation>>,
  /// The field where the aggregation is located in the document.
  #[serde(rename = "field")]
  field: Option<String>,
  /// Interval of the aggregation. Valid date interval values are second/seconds minute/minutes, hour/hours, day/days, week/weeks, month/months, and year/years.
  #[serde(rename = "interval")]
  interval: Option<String>,
  /// Used to indicate that anomaly detection should be performed. Anomaly detection is used to locate unusual datapoints within a time series.
  #[serde(rename = "anomaly")]
  anomaly: Option<bool>
}

impl Timeslice {
  pub fn new() -> Timeslice {
    Timeslice {
      type_: None,
      results: None,
      matching_results: None,
      aggregations: None,
      field: None,
      interval: None,
      anomaly: None
    }
  }

  pub fn set_type_(&mut self, type_: String) {
    self.type_ = Some(type_);
  }

  pub fn with_type_(mut self, type_: String) -> Timeslice {
    self.type_ = Some(type_);
    self
  }

  pub fn type_(&self) -> Option<&String> {
    self.type_.as_ref()
  }

  pub fn reset_type_(&mut self) {
    self.type_ = None;
  }

  pub fn set_results(&mut self, results: Vec<::models::AggregationResult>) {
    self.results = Some(results);
  }

  pub fn with_results(mut self, results: Vec<::models::AggregationResult>) -> Timeslice {
    self.results = Some(results);
    self
  }

  pub fn results(&self) -> Option<&Vec<::models::AggregationResult>> {
    self.results.as_ref()
  }

  pub fn reset_results(&mut self) {
    self.results = None;
  }

  pub fn set_matching_results(&mut self, matching_results: i32) {
    self.matching_results = Some(matching_results);
  }

  pub fn with_matching_results(mut self, matching_results: i32) -> Timeslice {
    self.matching_results = Some(matching_results);
    self
  }

  pub fn matching_results(&self) -> Option<&i32> {
    self.matching_results.as_ref()
  }

  pub fn reset_matching_results(&mut self) {
    self.matching_results = None;
  }

  pub fn set_aggregations(&mut self, aggregations: Vec<::models::QueryAggregation>) {
    self.aggregations = Some(aggregations);
  }

  pub fn with_aggregations(mut self, aggregations: Vec<::models::QueryAggregation>) -> Timeslice {
    self.aggregations = Some(aggregations);
    self
  }

  pub fn aggregations(&self) -> Option<&Vec<::models::QueryAggregation>> {
    self.aggregations.as_ref()
  }

  pub fn reset_aggregations(&mut self) {
    self.aggregations = None;
  }

  pub fn set_field(&mut self, field: String) {
    self.field = Some(field);
  }

  pub fn with_field(mut self, field: String) -> Timeslice {
    self.field = Some(field);
    self
  }

  pub fn field(&self) -> Option<&String> {
    self.field.as_ref()
  }

  pub fn reset_field(&mut self) {
    self.field = None;
  }

  pub fn set_interval(&mut self, interval: String) {
    self.interval = Some(interval);
  }

  pub fn with_interval(mut self, interval: String) -> Timeslice {
    self.interval = Some(interval);
    self
  }

  pub fn interval(&self) -> Option<&String> {
    self.interval.as_ref()
  }

  pub fn reset_interval(&mut self) {
    self.interval = None;
  }

  pub fn set_anomaly(&mut self, anomaly: bool) {
    self.anomaly = Some(anomaly);
  }

  pub fn with_anomaly(mut self, anomaly: bool) -> Timeslice {
    self.anomaly = Some(anomaly);
    self
  }

  pub fn anomaly(&self) -> Option<&bool> {
    self.anomaly.as_ref()
  }

  pub fn reset_anomaly(&mut self) {
    self.anomaly = None;
  }

}



