/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TopHits {
  /// The type of aggregation command used. For example: term, filter, max, min, etc.
  #[serde(rename = "type")]
  type_: Option<String>,
  #[serde(rename = "results")]
  results: Option<Vec<::models::AggregationResult>>,
  /// Number of matching results.
  #[serde(rename = "matching_results")]
  matching_results: Option<i32>,
  /// Aggregations returned by the Discovery service.
  #[serde(rename = "aggregations")]
  aggregations: Option<Vec<::models::QueryAggregation>>,
  /// Number of top hits returned by the aggregation.
  #[serde(rename = "size")]
  size: Option<i32>,
  #[serde(rename = "hits")]
  hits: Option<::models::TopHitsResults>
}

impl TopHits {
  pub fn new() -> TopHits {
    TopHits {
      type_: None,
      results: None,
      matching_results: None,
      aggregations: None,
      size: None,
      hits: None
    }
  }

  pub fn set_type_(&mut self, type_: String) {
    self.type_ = Some(type_);
  }

  pub fn with_type_(mut self, type_: String) -> TopHits {
    self.type_ = Some(type_);
    self
  }

  pub fn type_(&self) -> Option<&String> {
    self.type_.as_ref()
  }

  pub fn reset_type_(&mut self) {
    self.type_ = None;
  }

  pub fn set_results(&mut self, results: Vec<::models::AggregationResult>) {
    self.results = Some(results);
  }

  pub fn with_results(mut self, results: Vec<::models::AggregationResult>) -> TopHits {
    self.results = Some(results);
    self
  }

  pub fn results(&self) -> Option<&Vec<::models::AggregationResult>> {
    self.results.as_ref()
  }

  pub fn reset_results(&mut self) {
    self.results = None;
  }

  pub fn set_matching_results(&mut self, matching_results: i32) {
    self.matching_results = Some(matching_results);
  }

  pub fn with_matching_results(mut self, matching_results: i32) -> TopHits {
    self.matching_results = Some(matching_results);
    self
  }

  pub fn matching_results(&self) -> Option<&i32> {
    self.matching_results.as_ref()
  }

  pub fn reset_matching_results(&mut self) {
    self.matching_results = None;
  }

  pub fn set_aggregations(&mut self, aggregations: Vec<::models::QueryAggregation>) {
    self.aggregations = Some(aggregations);
  }

  pub fn with_aggregations(mut self, aggregations: Vec<::models::QueryAggregation>) -> TopHits {
    self.aggregations = Some(aggregations);
    self
  }

  pub fn aggregations(&self) -> Option<&Vec<::models::QueryAggregation>> {
    self.aggregations.as_ref()
  }

  pub fn reset_aggregations(&mut self) {
    self.aggregations = None;
  }

  pub fn set_size(&mut self, size: i32) {
    self.size = Some(size);
  }

  pub fn with_size(mut self, size: i32) -> TopHits {
    self.size = Some(size);
    self
  }

  pub fn size(&self) -> Option<&i32> {
    self.size.as_ref()
  }

  pub fn reset_size(&mut self) {
    self.size = None;
  }

  pub fn set_hits(&mut self, hits: ::models::TopHitsResults) {
    self.hits = Some(hits);
  }

  pub fn with_hits(mut self, hits: ::models::TopHitsResults) -> TopHits {
    self.hits = Some(hits);
    self
  }

  pub fn hits(&self) -> Option<&::models::TopHitsResults> {
    self.hits.as_ref()
  }

  pub fn reset_hits(&mut self) {
    self.hits = None;
  }

}



