/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TrainingExampleList {
  #[serde(rename = "examples")]
  examples: Option<Vec<::models::TrainingExample>>
}

impl TrainingExampleList {
  pub fn new() -> TrainingExampleList {
    TrainingExampleList {
      examples: None
    }
  }

  pub fn set_examples(&mut self, examples: Vec<::models::TrainingExample>) {
    self.examples = Some(examples);
  }

  pub fn with_examples(mut self, examples: Vec<::models::TrainingExample>) -> TrainingExampleList {
    self.examples = Some(examples);
    self
  }

  pub fn examples(&self) -> Option<&Vec<::models::TrainingExample>> {
    self.examples.as_ref()
  }

  pub fn reset_examples(&mut self) {
    self.examples = None;
  }

}



