/* 
 * Discovery
 *
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct XPathPatterns {
  #[serde(rename = "xpaths")]
  xpaths: Option<Vec<String>>
}

impl XPathPatterns {
  pub fn new() -> XPathPatterns {
    XPathPatterns {
      xpaths: None
    }
  }

  pub fn set_xpaths(&mut self, xpaths: Vec<String>) {
    self.xpaths = Some(xpaths);
  }

  pub fn with_xpaths(mut self, xpaths: Vec<String>) -> XPathPatterns {
    self.xpaths = Some(xpaths);
    self
  }

  pub fn xpaths(&self) -> Option<&Vec<String>> {
    self.xpaths.as_ref()
  }

  pub fn reset_xpaths(&mut self) {
    self.xpaths = None;
  }

}



